console:
  deploymentConfigs:
    - metadata:
        name: "{{.ApplicationName}}-{{.ConsoleName}}"
      spec:
        template:
          metadata:
            name: "{{.ApplicationName}}-{{.ConsoleName}}"
          spec:
            containers:
              - name: "{{.ApplicationName}}-{{.ConsoleName}}"
                ports:
                  - name: git-ssh
                    containerPort: 8001
                    protocol: TCP
  persistentVolumeClaims:
    - metadata:
        name: "{{.ApplicationName}}-{{.ConsoleName}}-claim"
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  services:
    - spec:
        ports:
          - name: git-ssh
            port: 8001
            targetPort: 8001
      metadata:
        name: "{{.ApplicationName}}-rhpamcentr"
## KIE Servers BEGIN
servers:
  ## RANGE BEGINS
  #{{ range $index, $Map := .ServerCount }}
  - deploymentConfigs:
      ## KIE server deployment config BEGIN
      - metadata:
          name: "{{.ApplicationName}}-kieserver-{{$index}}"
        spec:
          template:
            metadata:
              name: "{{.ApplicationName}}-kieserver-{{$index}}"
            spec:
              containers:
                - name: "{{.ApplicationName}}-kieserver-{{$index}}"
                  volumeMounts:
                    - name: "{{.ApplicationName}}-h2-pvol"
                      mountPath: "/opt/eap/standalone/data"
              volumes:
                ## H2 volume settings BEGIN
                - name: "{{.ApplicationName}}-h2-pvol"
                  persistentVolumeClaim:
                    claimName: "{{.ApplicationName}}-h2-claim-{{$index}}"
    ## KIE server deployment config END
    persistentVolumeClaims:
      ## H2 persistent volume claim BEGIN
      - metadata:
          name: "{{.ApplicationName}}-h2-claim-{{$index}}"
          labels:
            app: "{{.ApplicationName}}"
            service: "{{.ApplicationName}}-kieserver-{{$index}}"
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: "1Gi"
      ## H2 persistent volume claim END
#{{end}}
## RANGE ends
## KIE Servers END
