console:
  persistentVolumeClaims:
    - metadata:
        name: "{{.ApplicationName}}-{{.ConsoleName}}-claim"
        labels:
          app: "{{.ApplicationName}}"
      spec:
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 1Gi

  deploymentConfigs:
    - metadata:
        name: "{{.ApplicationName}}-{{.ConsoleName}}"
      spec:
        ## Replicas for Business Central
        replicas: 2
        template:
          metadata:
            name: "{{.ApplicationName}}-{{.ConsoleName}}"
          spec:
            containers:
              - name: "{{.ApplicationName}}-{{.ConsoleName}}"
                volumeMounts:
                  - name: "{{.ApplicationName}}-{{.ConsoleName}}-pvol"
                    mountPath: "/opt/eap/standalone/data/kie"
                ports:
                  - name: git-ssh
                    containerPort: 8001
                    protocol: TCP
                env:
                  - name: APPFORMER_ELASTIC_HOST
                    value: "{{.ApplicationName}}-rhpamindex"
                  - name: APPFORMER_JMS_BROKER_ADDRESS
                    value: "{{.ApplicationName}}-amq-tcp"
                  - name: APPFORMER_JMS_BROKER_USER
                    value: "jmsBrokserUser"
                  - name: APPFORMER_JMS_BROKER_PASSWORD
                    value: "{{.AdminPassword}}"
            volumes:
              - name: "{{.ApplicationName}}-{{.ConsoleName}}-pvol"
                persistentVolumeClaim:
                  claimName: "{{.ApplicationName}}-{{.ConsoleName}}-claim"

  services:
    - spec:
        ports:
          - name: git-ssh
            port: 8001
            targetPort: 8001
      metadata:
        name: "{{.ApplicationName}}-{{.ConsoleName}}"

## KIE smartrouter BEGIN
smartrouter:
  omit: true
## KIE smartrouter END
# MySQL/ES/AMQ BEGIN
others:
  - persistentVolumeClaims:
      - metadata:
          name: "{{.ApplicationName}}-mysql-claim"
          labels:
            app: "{{.ApplicationName}}"
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: "1Gi"

      - metadata:
          name: "{{.ApplicationName}}-rhpamindex-claim"
          labels:
            app: "{{.ApplicationName}}"
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: "1Gi"

    deploymentConfigs:
      - metadata:
          name: "{{.ApplicationName}}-rhpamindex"
          labels:
            app: "{{.ApplicationName}}"
            service: "{{.ApplicationName}}-rhpamindex"
        spec:
          strategy:
            type: Recreate
          triggers:
            - type: ImageChange
              imageChangeParams:
                automatic: true
                containerNames:
                  - "{{.ApplicationName}}-rhpamindex"
                from:
                  kind: ImageStreamTag
                  namespace: "openshift"
                  name: "rhpam{{.Version}}-businesscentral-indexing-openshift:{{.ImageTag}}"
            - type: ConfigChange
          replicas: 1
          selector:
            deploymentConfig: "{{.ApplicationName}}-rhpamindex"
          template:
            metadata:
              name: "{{.ApplicationName}}-rhpamindex"
              labels:
                deploymentConfig: "{{.ApplicationName}}-rhpamindex"
                app: "{{.ApplicationName}}"
            spec:
              terminationGracePeriodSeconds: 60
              containers:
                - name: "{{.ApplicationName}}-rhpamindex"
                  image: rhpam{{.Version}}-businesscentral-indexing-openshift
                  imagePullPolicy: Always
                  volumeMounts:
                    - name: "{{.ApplicationName}}-rhpamindex-pvol"
                      mountPath: "/opt/elasticsearch/data"
                  livenessProbe:
                    tcpSocket:
                      port: 9300
                    initialDelaySeconds: 15
                    timeoutSeconds: 1
                  readinessProbe:
                    httpGet:
                      scheme: HTTP
                      path: /_cluster/health
                      port: 9200
                    initialDelaySeconds: 15
                    timeoutSeconds: 2
                  ports:
                    - name: es
                      containerPort: 9300
                      protocol: TCP
                    - name: http
                      containerPort: 9200
                      protocol: TCP
                  env:
                    - name: ES_CLUSTER_NAME
                      value: ""
                    - name: ES_NODE_NAME
                      value: ""
                    - name: ES_TRANSPORT_HOST
                      value: ""
                    - name: ES_TRANSPORT_TCP_PORT
                      value: ""
                    - name: ES_HTTP_PORT
                      value: ""
                    - name: ES_HTTP_HOST
                      value: ""
                    - name: ES_JAVA_OPTS
                      value: ""
              volumes:
                - name: "{{.ApplicationName}}-rhpamindex-pvol"
                  persistentVolumeClaim:
                    claimName: "{{.ApplicationName}}-rhpamindex-claim"

      - metadata:
          name: "{{.ApplicationName}}-mysql"
          labels:
            app: "{{.ApplicationName}}"
        spec:
          strategy:
            type: Recreate
          triggers:
            - type: ImageChange
              imageChangeParams:
                automatic: true
                containerNames:
                  - "{{.ApplicationName}}-mysql"
                from:
                  kind: ImageStreamTag
                  namespace: "openshift"
                  name: "mysql:5.7"
            - type: ConfigChange
          replicas: 1
          selector:
            deploymentConfig: "{{.ApplicationName}}-mysql"
          template:
            metadata:
              name: "{{.ApplicationName}}-mysql"
              labels:
                deploymentConfig: "{{.ApplicationName}}-mysql"
                app: "{{.ApplicationName}}"
            spec:
              terminationGracePeriodSeconds: 60
              containers:
                - name: "{{.ApplicationName}}-mysql"
                  image: mysql
                  imagePullPolicy: Always
                  livenessProbe:
                    tcpSocket:
                      port: 3306
                    initialDelaySeconds: 30
                    timeoutSeconds: 1
                  readinessProbe:
                    exec:
                      command:
                        - "/bin/sh"
                        - "-i"
                        - "-c"
                        - "MYSQL_PWD=$MYSQL_PASSWORD mysql -h 127.0.0.1 -u $MYSQL_USER -D $MYSQL_DATABASE -e 'SELECT 1'"
                      port: 3306
                    initialDelaySeconds: 5
                    timeoutSeconds: 1
                  ports:
                    - containerPort: 3306
                      protocol: TCP
                  volumeMounts:
                    - mountPath: "/var/lib/mysql/data"
                      name: "{{.ApplicationName}}-mysql-pvol"
                  env:
                    - name: MYSQL_USER
                      value: "rhpam"
                    - name: MYSQL_PASSWORD
                      value: "{{.AdminPassword}}"
                    - name: MYSQL_DATABASE
                      value: "rhpam7"
              volumes:
                - name: "{{.ApplicationName}}-mysql-pvol"
                  persistentVolumeClaim:
                    claimName: "{{.ApplicationName}}-mysql-claim"

      - metadata:
          labels:
            app: "{{.ApplicationName}}"
          name: "{{.ApplicationName}}-amq"
        spec:
          replicas: 1
          selector:
            deploymentConfig: "{{.ApplicationName}}-amq"
          strategy:
            rollingParams:
              maxSurge: 0
            type: Rolling
          template:
            metadata:
              labels:
                app: "{{.ApplicationName}}"
                deploymentConfig: "{{.ApplicationName}}-amq"
              name: "{{.ApplicationName}}-amq"
            spec:
              containers:
                - env:
                    - name: AMQ_USER
                      value: "jmsBrokserUser"
                    - name: AMQ_PASSWORD
                      value: "{{.AdminPassword}}"
                    - name: AMQ_ROLE
                      value: admin
                    - name: AMQ_NAME
                      value: broker
                    - name: AMQ_TRANSPORTS
                      value: "openwire"
                    - name: AMQ_GLOBAL_MAX_SIZE
                      value: "100 gb"
                  image: "amq-broker-72-openshift"
                  imagePullPolicy: Always
                  readinessProbe:
                    exec:
                      command:
                        - "/bin/bash"
                        - "-c"
                        - "/opt/amq/bin/readinessProbe.sh"
                  lifecycle:
                    preStop:
                      exec:
                        command:
                          - /opt/amq/bin/shutdownHook.sh
                  name: "{{.ApplicationName}}-amq"
                  ports:
                    - containerPort: 8161
                      name: jolokia
                      protocol: TCP
                    - containerPort: 5672
                      name: amqp
                      protocol: TCP
                    - containerPort: 1883
                      name: mqtt
                      protocol: TCP
                    - containerPort: 61613
                      name: stomp
                      protocol: TCP
                    - containerPort: 61616
                      name: artemis
                      protocol: TCP
              terminationGracePeriodSeconds: 60
          triggers:
            - imageChangeParams:
                automatic: true
                containerNames:
                  - "{{.ApplicationName}}-amq"
                from:
                  kind: ImageStreamTag
                  namespace: "openshift"
                  name: "amq-broker-72-openshift:1.0"
              type: ImageChange
            - type: ConfigChange

    services:
      - spec:
          ports:
            - port: 61616
              targetPort: 61616
          selector:
            deploymentConfig: "{{.ApplicationName}}-amq"
        metadata:
          name: "{{.ApplicationName}}-amq-tcp"
          labels:
            app: "{{.ApplicationName}}"
            service: "{{.ApplicationName}}-amq"
          annotations:
            description: The broker's OpenWire port.

      - spec:
          ports:
            - port: 3306
              targetPort: 3306
          selector:
            deploymentConfig: "{{.ApplicationName}}-mysql"
        metadata:
          name: "{{.ApplicationName}}-mysql"
          labels:
            app: "{{.ApplicationName}}"
            service: "{{.ApplicationName}}-mysql"
          annotations:
            description: The MySQL server's port.

      - spec:
          ports:
            - name: rest
              port: 9200
              targetPort: 9200
            - name: transport
              port: 9300
              targetPort: 9300
          selector:
            deploymentConfig: "{{.ApplicationName}}-rhpamindex"
        metadata:
          name: "{{.ApplicationName}}-rhpamindex"
          labels:
            app: "{{.ApplicationName}}"
            service: "{{.ApplicationName}}-rhpamindex"
          annotations:
            description: All the Business Central Indexing Elasticsearch ports.

    routes:
      - id: "{{.ApplicationName}}-rhpamindex-http"
        metadata:
          name: "{{.ApplicationName}}-rhpamindex"
          labels:
            app: "{{.ApplicationName}}"
          annotations:
            description: Route for Business Central Indexing's Elasticsearch http service.
        spec:
          host: ""
          to:
            name: "{{.ApplicationName}}-rhpamindex"
          port:
            targetPort: rest

## MySQL/ES/AMQ END

## KIE Servers BEGIN
servers:
  ## RANGE BEGINS
  #{{ range $index, $Map := .ServerCount }}
  ## KIE server deployment config BEGIN
  - deploymentConfigs:
      - metadata:
          name: "{{.ApplicationName}}-kieserver-{{$index}}"
        spec:
          replicas: 2
          template:
            metadata:
              name: "{{.ApplicationName}}-kieserver-{{$index}}"
            spec:
              containers:
                - name: "{{.ApplicationName}}-kieserver-{{$index}}"
                  env:
                    - name: AUTO_CONFIGURE_EJB_TIMER
                      value: "true"
                    - name: KIE_SERVER_PERSISTENCE_DS
                      value: "java:/jboss/datasources/rhpam"
                    - name: DATASOURCES
                      value: "RHPAM"
                    - name: RHPAM_JNDI
                      value: "java:/jboss/datasources/rhpam"
                    - name: RHPAM_JTA
                      value: "true"
                    ## MySQL driver settings BEGIN
                    - name: RHPAM_DATABASE
                      value: "rhpam7"
                    - name: RHPAM_DRIVER
                      value: "mysql"
                    - name: KIE_SERVER_PERSISTENCE_DIALECT
                      value: "org.hibernate.dialect.MySQLDialect"
                    - name: RHPAM_USERNAME
                      value: "rhpam"
                    - name: RHPAM_PASSWORD
                      value: "{{.AdminPassword}}"
                    - name: RHPAM_SERVICE_HOST
                      value: "{{.ApplicationName}}-mysql"
                    - name: RHPAM_SERVICE_PORT
                      value: "3306"
                    - name: RHPAM_XA_CONNECTION_PROPERTY_URL
                      value: ""
                    ## MySQL driver settings END
                    - name: TIMER_SERVICE_DATA_STORE_REFRESH_INTERVAL
                      value: "60000"
  ## KIE server deployment config END
  #{{end}}
  ## RANGE ends
## KIE Servers END
