console:
  deploymentConfigs:
    - metadata:
        name: "[[.ApplicationName]]-[[.Console.Name]]"
      spec:
        containers:
          - name: "[[.ApplicationName]]-[[.Console.Name]]"
            env:
              - name: MAVEN_REPO_URL
                value: ""
              - name: MAVEN_REPO_USERNAME
                value: ""
              - name: MAVEN_REPO_PASSWORD
                value: ""

## KIE Servers BEGIN
servers:
  ## RANGE BEGINS
  #[[ range $index, $Map := .Servers ]]
    ## KIE server deployment config BEGIN
  - deploymentConfigs:
      - metadata:
          name: "[[.KieName]]"
          labels:
            app: "[[$.ApplicationName]]"
            application: "[[$.ApplicationName]]"
            service: "[[.KieName]]"
        spec:
          template:
            spec:
              containers:
                - name: "[[.KieName]]"
                  env:
                    - name: EXTERNAL_MAVEN_REPO_ID
                      value: ""
                    - name: EXTERNAL_MAVEN_REPO_URL
                      value: ""
                    - name: EXTERNAL_MAVEN_REPO_USERNAME
                      value: ""
                    - name: EXTERNAL_MAVEN_REPO_PASSWORD
                      value: ""
                    - name: KIE_SERVER_MODE
                      value: PRODUCTION
                    - name: KIE_SERVER_ROUTER_SERVICE
                      value: "[[$.ApplicationName]]-smartrouter"
                    - name: KIE_SERVER_ROUTER_PORT
                      value: "9000"
                    - name: KIE_SERVER_ROUTER_PROTOCOL
                      value: "http"
      ## KIE server deployment config END
  #[[end]]
  ## RANGE ends
  ## KIE Servers END
