console:
  deploymentConfigs:
    - metadata:
        name: "{{.ApplicationName}}-{{.Console.Name}}"
      spec:
        template:
          spec:
            containers:
              - name: "{{.ApplicationName}}-{{.Console.Name}}"
                ports:
                  - name: git-ssh
                    containerPort: 8001
                    protocol: TCP
            volumes:
              - name: "{{.ApplicationName}}-{{.Console.Name}}-pvol"
                emptyDir: {}
  persistentVolumeClaims:
    - metadata:
        name: "{{.ApplicationName}}-{{.Console.Name}}-claim"
        annotations:
          delete: "true"
  services:
    - metadata:
        name: "{{.ApplicationName}}-{{.Console.Name}}"
      spec:
        ports:
          - name: git-ssh
            port: 8001
            targetPort: 8001
  routes:
    - id: "{{.ApplicationName}}-{{.Console.Name}}-http"
      metadata:
        name: "{{.ApplicationName}}-{{.Console.Name}}-http"
        labels:
          app: "{{.ApplicationName}}"
          application: "{{.ApplicationName}}"
          service: "{{.ApplicationName}}-{{.Console.Name}}"
        annotations:
          description: Route for Business Central's http service.
          haproxy.router.openshift.io/timeout: 60s
      spec:
        to:
          name: "{{.ApplicationName}}-{{.Console.Name}}"
        port:
          targetPort: http
## KIE smartrouter BEGIN
smartrouter:
  omit: true
## KIE smartrouter END
## KIE Servers BEGIN
servers:
  ## RANGE BEGINS
  #{{ range $index, $Map := .Servers }}
  - deploymentConfigs:
      ## KIE server deployment config BEGIN
      - metadata:
          name: "{{.KieName}}-kieserver-{{.KieIndex}}"
        spec:
          template:
            metadata:
              name: "{{.KieName}}-kieserver-{{.KieIndex}}"
            spec:
              containers:
                - name: "{{.KieName}}-kieserver-{{.KieIndex}}"
                  env:
                    - name: DATASOURCES
                      value: "RHPAM"
                    - name: RHPAM_DATABASE
                      value: "rhpam7"
                    - name: RHPAM_JNDI
                      value: "java:/jboss/datasources/rhpam"
                    - name: RHPAM_JTA
                      value: "true"
                    - name: KIE_SERVER_PERSISTENCE_DS
                      value: "java:/jboss/datasources/rhpam"
                    ## H2 driver settings BEGIN
                    - name: RHPAM_DRIVER
                      value: "h2"
                    - name: RHPAM_USERNAME
                      value: "sa"
                    - name: RHPAM_PASSWORD
                      value: "{{$.AdminPassword}}"
                    - name: RHPAM_SERVICE_HOST
                      value: "dummy_ignored"
                    - name: RHPAM_SERVICE_PORT
                      value: "12345"
                    - name: KIE_SERVER_PERSISTENCE_DIALECT
                      value: "org.hibernate.dialect.H2Dialect"
                    - name: RHPAM_XA_CONNECTION_PROPERTY_URL
                      value: "jdbc:h2:/opt/eap/standalone/data/rhpam"
                    ## H2 driver settings END
                    - name: KIE_SERVER_ROUTE_NAME
                      value: "{{.KieName}}-kieserver-{{.KieIndex}}-http"
                    - name: KIE_SERVER_PROTOCOL
                    - name: KIE_SERVER_PORT
                    - name: FILTERS
                      value: "AC_ALLOW_ORIGIN,AC_ALLOW_METHODS,AC_ALLOW_HEADERS,AC_ALLOW_CREDENTIALS,AC_MAX_AGE"
                    - name: AC_ALLOW_ORIGIN_FILTER_RESPONSE_HEADER_NAME
                      value: "Access-Control-Allow-Origin"
                    - name: AC_ALLOW_ORIGIN_FILTER_RESPONSE_HEADER_VALUE
                      value: "*"
                    - name: AC_ALLOW_METHODS_FILTER_RESPONSE_HEADER_NAME
                      value: "Access-Control-Allow-Methods"
                    - name: AC_ALLOW_METHODS_FILTER_RESPONSE_HEADER_VALUE
                      value: "GET, POST, OPTIONS, PUT"
                    - name: AC_ALLOW_HEADERS_FILTER_RESPONSE_HEADER_NAME
                      value: "Access-Control-Allow-Headers"
                    - name: AC_ALLOW_HEADERS_FILTER_RESPONSE_HEADER_VALUE
                      value: "Accept, Authorization, Content-Type, X-Requested-With"
                    - name: AC_ALLOW_CREDENTIALS_FILTER_RESPONSE_HEADER_NAME
                      value: "Access-Control-Allow-Credentials"
                    - name: AC_ALLOW_CREDENTIALS_FILTER_RESPONSE_HEADER_VALUE
                      value: "true"
                    - name: AC_MAX_AGE_FILTER_RESPONSE_HEADER_NAME
                      value: "Access-Control-Max-Age"
                    - name: AC_MAX_AGE_FILTER_RESPONSE_HEADER_VALUE
                      value: "1"
                  volumeMounts:
                    - name: "{{.KieName}}-h2-pvol"
                      mountPath: "/opt/eap/standalone/data"
              volumes:
                ## H2 volume settings BEGIN
                - name: "{{.KieName}}-h2-pvol"
                  emptyDir: {}
    ## KIE server deployment config END
    ## KIE server route BEGIN
    routes:
      - id: "{{.KieName}}-kieserver-{{.KieIndex}}-http"
        metadata:
          name: "{{.KieName}}-kieserver-{{.KieIndex}}-http"
          labels:
            app: "{{$.ApplicationName}}"
            application: "{{$.ApplicationName}}"
            service: "{{.KieName}}-kieserver-{{.KieIndex}}"
          annotations:
            description: Route for KIE server's http service.
            haproxy.router.openshift.io/timeout: 60s
        spec:
          to:
            name: "{{.KieName}}-kieserver-{{.KieIndex}}"
          port:
            targetPort: http
    ## KIE server route END
#{{end}}
## RANGE ends
## KIE Servers END
