console:
  deploymentConfigs:
    - metadata:
        name: "[[.ApplicationName]]-[[.Console.Name]]"
      spec:
        template:
          metadata:
            name: "[[.ApplicationName]]-[[.Console.Name]]"
          spec:
            containers:
              - name: "[[.ApplicationName]]-[[.Console.Name]]"
                ports:
                  - name: git-ssh
                    containerPort: 8001
                    protocol: TCP
  persistentVolumeClaims:
    - metadata:
        name: "[[.ApplicationName]]-[[.Console.Name]]-claim"
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  services:
    - spec:
        ports:
          - name: git-ssh
            port: 8001
            targetPort: 8001
      metadata:
        name: "[[.ApplicationName]]-[[.Console.Name]]"
## KIE smartrouter BEGIN
smartRouter:
  omit: true
## KIE smartrouter END
## KIE Servers BEGIN
servers:
  ## RANGE BEGINS
  #[[ range $index, $Map := .Servers ]]
  - deploymentConfigs:
      ## KIE server deployment config BEGIN
      - metadata:
          name: "[[.KieName]][[.KieIndex]]"
        spec:
          template:
            metadata:
              name: "[[.KieName]][[.KieIndex]]"
            spec:
              containers:
                - name: "[[.KieName]][[.KieIndex]]"
                  env:
                    - name: DATASOURCES
                      value: "RHPAM"
                    - name: RHPAM_DATABASE
                      value: "rhpam7"
                    - name: RHPAM_JNDI
                      value: "java:/jboss/datasources/rhpam"
                    - name: RHPAM_JTA
                      value: "true"
                    - name: KIE_SERVER_PERSISTENCE_DS
                      value: "java:/jboss/datasources/rhpam"
                    ## H2 driver settings BEGIN
                    - name: RHPAM_DRIVER
                      value: "h2"
                    - name: RHPAM_USERNAME
                      value: "sa"
                    - name: RHPAM_PASSWORD
                      value: "[[$.AdminPassword]]"
                    - name: RHPAM_SERVICE_HOST
                      value: "dummy_ignored"
                    - name: RHPAM_SERVICE_PORT
                      value: "12345"
                    - name: KIE_SERVER_PERSISTENCE_DIALECT
                      value: "org.hibernate.dialect.H2Dialect"
                    - name: RHPAM_XA_CONNECTION_PROPERTY_URL
                      value: "jdbc:h2:/opt/eap/standalone/data/rhpam"
                  volumeMounts:
                    - name: "[[.KieName]]-h2-pvol"
                      mountPath: "/opt/eap/standalone/data"
              volumes:
                ## H2 volume settings BEGIN
                - name: "[[.KieName]]-h2-pvol"
                  persistentVolumeClaim:
                    claimName: "[[.KieName]][[.KieIndex]]-h2-claim"
    ## KIE server deployment config END
    persistentVolumeClaims:
      ## H2 persistent volume claim BEGIN
      - metadata:
          name: "[[.KieName]][[.KieIndex]]-h2-claim"
          labels:
            app: "[[$.ApplicationName]]"
            application: "[[$.ApplicationName]]"
            service: "[[.KieName]][[.KieIndex]]"
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: "1Gi"
      ## H2 persistent volume claim END
#[[end]]
## RANGE ends
## KIE Servers END
