apiVersion: app.kiegroup.org/v2
kind: KieApp
metadata:
  name: rhapm-secret
  annotations:
    consoleName: snippet-secret-credentials-config
    consoleTitle: Use secret credentials
    consoleDesc: Use this snippet to specify admin credentials with a secret
    consoleSnippet: true
spec:
  commonConfig:
    # By default is the cr.Name
    applicationName: other
    # Secret containing username and password keys
    secretAdminCredentials: kie-admin-credentials
