apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kieapps.app.kiegroup.org
spec:
  group: app.kiegroup.org
  names:
    kind: KieApp
    listKind: KieAppList
    plural: kieapps
    singular: kieapp
  scope: Namespaced
  version: v1
