apiVersion: apps/v1
kind: Deployment
metadata:
  name: bamoe-business-automation-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: bamoe-business-automation-operator
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: bamoe-business-automation-operator
    spec:
      containers:
      - command:
        - kie-cloud-operator
        env:
        - name: OPERATOR_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['name']
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: OPERATOR_UI
          value: "true"
        - name: DEBUG
          value: "false"
        - name: RELATED_IMAGE_PAM_KIESERVER_IMAGE_8.0.3
          value: registry.redhat.io/ibm-bamoe/bamoe-kieserver-rhel8:8.0.3
        - name: RELATED_IMAGE_PAM_CONTROLLER_IMAGE_8.0.3
          value: registry.redhat.io/ibm-bamoe/bamoe-controller-rhel8:8.0.3
        - name: RELATED_IMAGE_PAM_BC_IMAGE_8.0.3
          value: registry.redhat.io/ibm-bamoe/bamoe-businesscentral-rhel8:8.0.3
        - name: RELATED_IMAGE_PAM_BC_MONITORING_IMAGE_8.0.3
          value: registry.redhat.io/ibm-bamoe/bamoe-businesscentral-monitoring-rhel8:8.0.3
        - name: RELATED_IMAGE_PAM_SMARTROUTER_IMAGE_8.0.3
          value: registry.redhat.io/ibm-bamoe/bamoe-smartrouter-rhel8:8.0.3
        - name: RELATED_IMAGE_PAM_PROCESS_MIGRATION_IMAGE_8.0.3
          value: registry.redhat.io/ibm-bamoe/bamoe-process-migration-rhel8:8.0.3
        - name: RELATED_IMAGE_PAM_DASHBUILDER_IMAGE_8.0.3
          value: registry.redhat.io/ibm-bamoe/bamoe-dashbuilder-rhel8:8.0.3
        - name: RELATED_IMAGE_OSE_CLI_IMAGE_8.0.3
          value: registry.redhat.io/openshift4/ose-cli:v4.12
        - name: RELATED_IMAGE_MYSQL_PROXY_IMAGE_8.0.3
          value: registry.redhat.io/rhscl/mysql-80-rhel7:latest
        - name: RELATED_IMAGE_POSTGRESQL_PROXY_IMAGE_8.0.3
          value: registry.redhat.io/rhscl/postgresql-13-rhel7:latest
        - name: RELATED_IMAGE_DATAGRID_IMAGE_8.0.3
          value: registry.redhat.io/datagrid/datagrid-8-rhel8:1.1
        - name: RELATED_IMAGE_BROKER_IMAGE_8.0.3
          value: registry.redhat.io/amq7/amq-broker-rhel8:7.9
        - name: RELATED_IMAGE_PAM_KIESERVER_IMAGE_8.0.2
          value: registry.redhat.io/ibm-bamoe/bamoe-kieserver-rhel8:8.0.2
        - name: RELATED_IMAGE_PAM_CONTROLLER_IMAGE_8.0.2
          value: registry.redhat.io/ibm-bamoe/bamoe-controller-rhel8:8.0.2
        - name: RELATED_IMAGE_PAM_BC_IMAGE_8.0.2
          value: registry.redhat.io/ibm-bamoe/bamoe-businesscentral-rhel8:8.0.2
        - name: RELATED_IMAGE_PAM_BC_MONITORING_IMAGE_8.0.2
          value: registry.redhat.io/ibm-bamoe/bamoe-businesscentral-monitoring-rhel8:8.0.2
        - name: RELATED_IMAGE_PAM_SMARTROUTER_IMAGE_8.0.2
          value: registry.redhat.io/ibm-bamoe/bamoe-smartrouter-rhel8:8.0.2
        - name: RELATED_IMAGE_PAM_PROCESS_MIGRATION_IMAGE_8.0.2
          value: registry.redhat.io/ibm-bamoe/bamoe-process-migration-rhel8:8.0.2
        - name: RELATED_IMAGE_PAM_DASHBUILDER_IMAGE_8.0.2
          value: registry.redhat.io/ibm-bamoe/bamoe-dashbuilder-rhel8:8.0.2
        - name: RELATED_IMAGE_OSE_CLI_IMAGE_8.0.2
          value: registry.redhat.io/openshift4/ose-cli:v4.12
        - name: RELATED_IMAGE_MYSQL_PROXY_IMAGE_8.0.2
          value: registry.redhat.io/rhscl/mysql-80-rhel7:latest
        - name: RELATED_IMAGE_POSTGRESQL_PROXY_IMAGE_8.0.2
          value: registry.redhat.io/rhscl/postgresql-12-rhel7:latest
        - name: RELATED_IMAGE_DATAGRID_IMAGE_8.0.2
          value: registry.redhat.io/jboss-datagrid-7/datagrid73-openshift:1.6
        - name: RELATED_IMAGE_BROKER_IMAGE_8.0.2
          value: registry.redhat.io/amq7/amq-broker:7.8
        - name: RELATED_IMAGE_OAUTH_PROXY_IMAGE_LATEST
          value: registry.redhat.io/openshift4/ose-oauth-proxy:latest
        - name: RELATED_IMAGE_OAUTH_PROXY_IMAGE_4.12
          value: registry.redhat.io/openshift4/ose-oauth-proxy:v4.12
        - name: RELATED_IMAGE_OAUTH_PROXY_IMAGE_4.11
          value: registry.redhat.io/openshift4/ose-oauth-proxy:v4.11
        - name: RELATED_IMAGE_OAUTH_PROXY_IMAGE_4.10
          value: registry.redhat.io/openshift4/ose-oauth-proxy:v4.10
        image: quay.io/kiegroup/kie-cloud-operator:8.0.3
        imagePullPolicy: Always
        name: bamoe-business-automation-operator
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          runAsNonRoot: true
      securityContext:
        runAsNonRoot: true
      serviceAccountName: bamoe-business-automation-operator
