apiVersion: apps/v1
kind: Deployment
metadata:
  name: business-automation-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: business-automation-operator
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: business-automation-operator
    spec:
      containers:
      - command:
        - kie-cloud-operator
        env:
        - name: OPERATOR_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['name']
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: OPERATOR_UI
          value: "true"
        - name: DEBUG
          value: "false"
        - name: DM_KIESERVER_IMAGE_7.9.0
          value: registry.redhat.io/rhdm-7/rhdm-kieserver-rhel8:7.9.0
        - name: DM_CONTROLLER_IMAGE_7.9.0
          value: registry.redhat.io/rhdm-7/rhdm-controller-rhel8:7.9.0
        - name: DM_DC_IMAGE_7.9.0
          value: registry.redhat.io/rhdm-7/rhdm-decisioncentral-rhel8:7.9.0
        - name: PAM_KIESERVER_IMAGE_7.9.0
          value: registry.redhat.io/rhpam-7/rhpam-kieserver-rhel8:7.9.0
        - name: PAM_CONTROLLER_IMAGE_7.9.0
          value: registry.redhat.io/rhpam-7/rhpam-controller-rhel8:7.9.0
        - name: PAM_BC_IMAGE_7.9.0
          value: registry.redhat.io/rhpam-7/rhpam-businesscentral-rhel8:7.9.0
        - name: PAM_BC_MONITORING_IMAGE_7.9.0
          value: registry.redhat.io/rhpam-7/rhpam-businesscentral-monitoring-rhel8:7.9.0
        - name: PAM_SMARTROUTER_IMAGE_7.9.0
          value: registry.redhat.io/rhpam-7/rhpam-smartrouter-rhel8:7.9.0
        - name: PAM_PROCESS_MIGRATION_IMAGE_7.9.0
          value: registry.redhat.io/rhpam-7/rhpam-process-migration-rhel8:7.9.0
        - name: OSE_CLI_IMAGE_7.9.0
          value: registry.redhat.io/openshift3/ose-cli:v3.11
        - name: MYSQL_PROXY_IMAGE_7.9.0
          value: registry.redhat.io/rhscl/mysql-80-rhel7:latest
        - name: POSTGRESQL_PROXY_IMAGE_7.9.0
          value: registry.redhat.io/rhscl/postgresql-10-rhel7:latest
        - name: DATAGRID_IMAGE_7.9.0
          value: registry.redhat.io/jboss-datagrid-7/datagrid73-openshift:1.6
        - name: BROKER_IMAGE_7.9.0
          value: registry.redhat.io/amq7/amq-broker:7.7
        - name: DM_KIESERVER_IMAGE_7.8.1
          value: registry.redhat.io/rhdm-7/rhdm-kieserver-rhel8:7.8.1
        - name: DM_CONTROLLER_IMAGE_7.8.1
          value: registry.redhat.io/rhdm-7/rhdm-controller-rhel8:7.8.1
        - name: DM_DC_IMAGE_7.8.1
          value: registry.redhat.io/rhdm-7/rhdm-decisioncentral-rhel8:7.8.1
        - name: PAM_KIESERVER_IMAGE_7.8.1
          value: registry.redhat.io/rhpam-7/rhpam-kieserver-rhel8:7.8.1
        - name: PAM_CONTROLLER_IMAGE_7.8.1
          value: registry.redhat.io/rhpam-7/rhpam-controller-rhel8:7.8.1
        - name: PAM_BC_IMAGE_7.8.1
          value: registry.redhat.io/rhpam-7/rhpam-businesscentral-rhel8:7.8.1
        - name: PAM_BC_MONITORING_IMAGE_7.8.1
          value: registry.redhat.io/rhpam-7/rhpam-businesscentral-monitoring-rhel8:7.8.1
        - name: PAM_SMARTROUTER_IMAGE_7.8.1
          value: registry.redhat.io/rhpam-7/rhpam-smartrouter-rhel8:7.8.1
        - name: PAM_PROCESS_MIGRATION_IMAGE_7.8.1
          value: registry.redhat.io/rhpam-7/rhpam-process-migration-rhel8:7.8.1
        - name: OSE_CLI_IMAGE_7.8.1
          value: registry.redhat.io/openshift3/ose-cli:v3.11
        - name: MYSQL_PROXY_IMAGE_7.8.1
          value: registry.redhat.io/rhscl/mysql-80-rhel7:latest
        - name: POSTGRESQL_PROXY_IMAGE_7.8.1
          value: registry.redhat.io/rhscl/postgresql-10-rhel7:latest
        - name: DATAGRID_IMAGE_7.8.1
          value: registry.redhat.io/jboss-datagrid-7/datagrid73-openshift:1.5
        - name: BROKER_IMAGE_7.8.1
          value: registry.redhat.io/amq7/amq-broker:7.6
        - name: DM_KIESERVER_IMAGE_7.8.0
          value: registry.redhat.io/rhdm-7/rhdm-kieserver-rhel8:7.8.0
        - name: DM_CONTROLLER_IMAGE_7.8.0
          value: registry.redhat.io/rhdm-7/rhdm-controller-rhel8:7.8.0
        - name: DM_DC_IMAGE_7.8.0
          value: registry.redhat.io/rhdm-7/rhdm-decisioncentral-rhel8:7.8.0
        - name: PAM_KIESERVER_IMAGE_7.8.0
          value: registry.redhat.io/rhpam-7/rhpam-kieserver-rhel8:7.8.0
        - name: PAM_CONTROLLER_IMAGE_7.8.0
          value: registry.redhat.io/rhpam-7/rhpam-controller-rhel8:7.8.0
        - name: PAM_BC_IMAGE_7.8.0
          value: registry.redhat.io/rhpam-7/rhpam-businesscentral-rhel8:7.8.0
        - name: PAM_BC_MONITORING_IMAGE_7.8.0
          value: registry.redhat.io/rhpam-7/rhpam-businesscentral-monitoring-rhel8:7.8.0
        - name: PAM_SMARTROUTER_IMAGE_7.8.0
          value: registry.redhat.io/rhpam-7/rhpam-smartrouter-rhel8:7.8.0
        - name: PAM_PROCESS_MIGRATION_IMAGE_7.8.0
          value: registry.redhat.io/rhpam-7/rhpam-process-migration-rhel8:7.8.0
        - name: OSE_CLI_IMAGE_7.8.0
          value: registry.redhat.io/openshift3/ose-cli:v3.11
        - name: MYSQL_PROXY_IMAGE_7.8.0
          value: registry.redhat.io/rhscl/mysql-80-rhel7:latest
        - name: POSTGRESQL_PROXY_IMAGE_7.8.0
          value: registry.redhat.io/rhscl/postgresql-10-rhel7:latest
        - name: DATAGRID_IMAGE_7.8.0
          value: registry.redhat.io/jboss-datagrid-7/datagrid73-openshift:1.5
        - name: BROKER_IMAGE_7.8.0
          value: registry.redhat.io/amq7/amq-broker:7.6
        - name: OAUTH_PROXY_IMAGE_LATEST
          value: registry.redhat.io/openshift4/ose-oauth-proxy:latest
        - name: OAUTH_PROXY_IMAGE_4.6
          value: registry.redhat.io/openshift4/ose-oauth-proxy:v4.6
        - name: OAUTH_PROXY_IMAGE_4.5
          value: registry.redhat.io/openshift4/ose-oauth-proxy:v4.5
        - name: OAUTH_PROXY_IMAGE_4.4
          value: registry.redhat.io/openshift4/ose-oauth-proxy:v4.4
        - name: OAUTH_PROXY_IMAGE_4.3
          value: registry.redhat.io/openshift4/ose-oauth-proxy:v4.3
        - name: OAUTH_PROXY_IMAGE_4.2
          value: registry.redhat.io/openshift4/ose-oauth-proxy:v4.2
        - name: OAUTH_PROXY_IMAGE_4.1
          value: registry.redhat.io/openshift4/ose-oauth-proxy:v4.1
        - name: OAUTH_PROXY_IMAGE_3
          value: registry.redhat.io/openshift3/oauth-proxy:latest
        image: quay.io/kiegroup/kie-cloud-operator:7.9.0
        imagePullPolicy: Always
        name: business-automation-operator
        resources: {}
      serviceAccountName: business-automation-operator
