apiVersion: apps/v1
kind: Deployment
metadata:
  name: kie-cloud-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kie-cloud-operator
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: kie-cloud-operator
    spec:
      containers:
      - command:
        - kie-cloud-operator
        env:
        - name: OPERATOR_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['name']
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: OPERATOR_UI
          value: "true"
        - name: DEBUG
          value: "false"
        image: quay.io/kiegroup/kie-cloud-operator:1.3.1
        imagePullPolicy: Always
        name: kie-cloud-operator
        resources: {}
      serviceAccountName: kie-cloud-operator
