apiVersion: apps/v1
kind: Deployment
metadata:
  name: kie-cloud-operator
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      name: kie-cloud-operator
  template:
    metadata:
      labels:
        name: kie-cloud-operator
    spec:
      serviceAccountName: kie-cloud-operator
      containers:
        - name: kie-cloud-operator
          image: quay.io/kiegroup/kie-cloud-operator:1.2.1
          command:
            - kie-cloud-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['name']
            - name: DEBUG
              value: "false"
            - name: OPERATOR_UI
              value: "true"
            #- name: INSECURE
            #  value: ""
            #- name: REGISTRY
            #  value: ""
