apiVersion: kiegroup.org/v1
kind: App
metadata:
  name: trial-env
spec:
  environment: trial-ephemeral
  console:
    resources:
      requests:
        memory: 1Gi
      limits:
        memory: 2Gi
    env:
    - name: key1
      value: value1
    - name: key2
      value: value2
  server:
    resources:
      requests:
        memory:
      limits:
        memory: 2Gi
