apiVersion: app.kiegroup.org/v2
kind: KieApp
metadata:
  name: rhpam-ldap
spec:
  environment: rhpam-production
  auth:
    ldap:
      url: ldaps://myldap.example.com
      bindDN: uid=admin,ou=users,ou=exmample,ou=com
      bindCredential: s3cret
      baseCtxDN: ou=users,ou=example,ou=com
      baseFilter: (uid={0})
      searchScope: SUBTREE_SCOPE
      roleAttributeID: memberOf
      rolesCtxDN: ou=groups,ou=example,ou=com
      roleFilter: (memberOf={1})
      defaultRole: guest
    roleMapper:
      rolesProperties: /config/roleMapper.properties
      replaceRole: true
