deploymentconfigs:
- metadata:
    labels:
      app: default
      service: kieserver
    name: default-kieserver
  spec:
    replicas: 1
    selector:
      app: default
      service: kieserver
    strategy:
      resources: {}
      type: Recreate
    template:
      metadata:
        labels:
          app: default
          service: kieserver
        name: default-kieserver
      spec:
        containers:
        - env:
          - name: DROOLS_SERVER_FILTER_CLASSES
            value: "true"
          - name: KIE_ADMIN_USER
            value: adminUser
          - name: RHPAMCENTR_MAVEN_REPO_PASSWORD
            value: RedHat
          - name: RHPAMCENTR_MAVEN_REPO_PATH
            value: /maven2/
          - name: RHPAMCENTR_MAVEN_REPO_USERNAME
            value: mavenUser
          - name: KIE_SERVER_CONTROLLER_SERVICE
            value: default-rhpamcentr
          - name: KIE_MBEANS
            value: enabled
          - name: KIE_SERVER_CONTROLLER_PWD
            value: RedHat
          - name: MAVEN_REPOS
            value: RHPAMCENTR,EXTERNAL
          - name: RHPAMCENTR_MAVEN_REPO_SERVICE
            value: default-rhpamcentr
          - name: SSO_OPENIDCONNECT_DEPLOYMENTS
            value: ROOT.war
          - name: EXECUTION_SERVER_ROUTE_NAME
            value: default-kieserver
          - name: KIE_ADMIN_PWD
            value: RedHat
          - name: KIE_SERVER_BYPASS_AUTH_USER
            value: "false"
          - name: KIE_SERVER_CONTROLLER_USER
            value: controllerUser
          - name: KIE_SERVER_PWD
            value: RedHat
          - name: KIE_SERVER_USER
            value: executionUser
          - name: KIE_SERVER_CONTROLLER_PROTOCOL
            value: ws
          image: rhpam70-kieserver-openshift
          imagePullPolicy: Always
          livenessProbe:
            exec:
              command:
              - /bin/bash
              - -c
              - curl --fail --silent -u adminUser:RedHat http://localhost:8080/services/rest/server/healthcheck
            initialDelaySeconds: 180
            periodSeconds: 15
            timeoutSeconds: 2
          name: default-kieserver
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - /bin/bash
              - -c
              - curl --fail --silent -u adminUser:RedHat http://localhost:8080/services/rest/server/readycheck
            failureThreshold: 6
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 2
          resources:
            limits:
              memory: 1Gi
        terminationGracePeriodSeconds: 60
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - default-kieserver
        from:
          kind: ImageStreamTag
          name: rhpam70-kieserver-openshift:1.2
          namespace: openshift
      type: ImageChange
    - type: ConfigChange
routes:
- metadata:
    labels:
      app: default
      service: kieserver
    name: default-kieserver
  spec:
    port:
      targetPort: http
    to:
      name: default-kieserver
services:
- metadata:
    labels:
      app: default
      service: kieserver
    name: default-kieserver
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: default
      service: kieserver
