console:
  deploymentConfigs:
    - metadata:
        name: "[[.ApplicationName]]-[[.Console.Name]]"
      spec:
        template:
          spec:
            containers:
              - name: "[[.ApplicationName]]-[[.Console.Name]]"
                env:
                  - name: KIE_SERVER_HOST
                resources:
                  limits:
                    memory: 2Gi
            volumes:
              - name: "[[.ApplicationName]]-[[.Console.Name]]-pvol"
                emptyDir: {}
  persistentVolumeClaims:
    - metadata:
        name: "[[.ApplicationName]]-[[.Console.Name]]-claim"
        annotations:
          delete: "true"
  routes:
    - id: "[[.ApplicationName]]-[[.Console.Name]]-http"
      metadata:
        name: "[[.ApplicationName]]-[[.Console.Name]]-http"
        labels:
          app: "[[.ApplicationName]]"
          application: "[[.ApplicationName]]"
          service: "[[.ApplicationName]]-[[.Console.Name]]"
        annotations:
          description: Route for Business Central's http service.
          haproxy.router.openshift.io/timeout: 60s
      spec:
        to:
          name: "[[.ApplicationName]]-[[.Console.Name]]"
        port:
          targetPort: http
## KIE Servers BEGIN
servers:
  ## RANGE BEGINS
  #[[ range $index, $Map := .Servers ]]
  - deploymentConfigs:
      ## KIE server deployment config BEGIN
      - metadata:
          name: "[[.KieName]]"
        spec:
          template:
            metadata:
              name: "[[.KieName]]"
            spec:
              containers:
                - name: "[[.KieName]]"
                  resources:
                    limits:
                      memory: 1Gi
    ## KIE server deployment config END
    ## KIE server route BEGIN
    routes:
      - id: "[[.KieName]]-http"
        metadata:
          name: "[[.KieName]]-http"
          labels:
            app: "[[$.ApplicationName]]"
            application: "[[$.ApplicationName]]"
            service: "[[.KieName]]"
          annotations:
            description: Route for KIE server's http service.
            haproxy.router.openshift.io/balance: source
            haproxy.router.openshift.io/timeout: 60s
        spec:
          to:
            name: "[[.KieName]]"
          port:
            targetPort: http
    ## KIE server route END
#[[end]]
## RANGE ends
## KIE Servers END
