## KIE ProcessMigration BEGIN
processMigration:
  ## KIE ProcessMigration Deployment config BEGIN
  deploymentConfigs:
    - metadata:
        name: "[[.ApplicationName]]-process-migration"
      spec:
        template:
          spec:
            initContainers:
              - command:
                  [
                    "/bin/bash",
                    "-c",
                    ">-
                    replicas=$(oc get dc [[.ApplicationName]]-process-migration-mysql -o=jsonpath='{.status.availableReplicas}'); until '[' $replicas -gt 0 ']'; do echo waiting for [[.ApplicationName]]-process-migration-mysql; replicas=$(oc get dc [[.ApplicationName]]-process-migration-mysql -o=jsonpath='{.status.availableReplicas}'); sleep 2; done;",
                  ]
                image: "[[$.Constants.OseCliImageURL]]"
                imagePullPolicy: IfNotPresent
                name: "[[.ApplicationName]]-process-migration-mysql-init"
                terminationMessagePolicy: FallbackToLogsOnError
            containers:
              - name: "[[.ApplicationName]]-process-migration"
                env:
                  - name: JBOSS_KIE_EXTRA_CLASSPATH
                    value: "/opt/rhpam-process-migration/drivers/mariadb-java-client.jar"
  ## KIE ProcessMigration Deployment config END
  ## KIE ProcessMigration ConfigMap BEGIN
  configMaps:
    - metadata:
        name: "[[.ApplicationName]]-process-migration"
      data:
        project-overrides.yml: |-
          kieservers:
            #[[range $index, $Map := .ProcessMigration.KieServerClients]]
            - host: [[.Host]]
              username: [[.Username]]
              password: [[.Password]]
            #[[end]]
          thorntail:
            datasources:
              data-sources:
                pimDS:
                  driver-name: mariadb
                  connection-url: jdbc:mariadb://[[.ApplicationName]]-process-migration-mysql:3306/pimdb?useUnicode=true&useSSL=false&serverTimezone=UTC
                  user-name: pim
                  password: "[[$.DBPassword]]"
  ## KIE ProcessMigration ConfigMap END
## KIE ProcessMigration END