## KIE Servers BEGIN
servers:
  ## RANGE BEGINS
  #[[ range $index, $Map := .Servers ]]
  ## KIE server deployment config BEGIN
  - deploymentConfigs:
      - metadata:
          name: "[[.KieName]]"
        spec:
          template:
            spec:
              initContainers:
                - command:
                    [
                      "/bin/bash",
                      "-c",
                      ">-
                       replicas=$(oc get dc [[.KieName]]-mysql -o=jsonpath='{.status.availableReplicas}'); until '[' $replicas -gt 0 ']'; do echo waiting for [[.KieName]]-mysql; replicas=$(oc get dc [[.KieName]]-mysql -o=jsonpath='{.status.availableReplicas}'); sleep 2; done;",
                    ]
                  image: "[[$.Constants.OseCliImageURL]]"
                  imagePullPolicy: IfNotPresent
                  name: "[[.KieName]]-mysql-init"
                  terminationMessagePolicy: FallbackToLogsOnError
              containers:
                - name: "[[.KieName]]"
                  env:
                    ## MySQL driver settings BEGIN
                    - name: DATASOURCES
                      value: "RHPAM"
                    - name: RHPAM_DATABASE
                      value: "rhpam7"
                    - name: RHPAM_JNDI
                      value: "java:/jboss/datasources/rhpam"
                    - name: RHPAM_JTA
                      value: "true"
                    - name: KIE_SERVER_PERSISTENCE_DS
                      value: "java:/jboss/datasources/rhpam"
                    - name: RHPAM_DRIVER
                      value: "mariadb"
                    - name: KIE_SERVER_PERSISTENCE_DIALECT
                      value: "org.hibernate.dialect.MySQL57Dialect"
                    - name: RHPAM_USERNAME
                      value: "rhpam"
                    - name: RHPAM_PASSWORD
                      value: "[[$.DBPassword]]"
                    - name: RHPAM_SERVICE_HOST
                      value: "[[.KieName]]-mysql"
                    - name: RHPAM_SERVICE_PORT
                      value: "3306"
                    - name: RHPAM_CONNECTION_CHECKER
                      value: "org.jboss.jca.adapters.jdbc.extensions.mysql.MySQLValidConnectionChecker"
                    - name: RHPAM_EXCEPTION_SORTER
                      value: "org.jboss.jca.adapters.jdbc.extensions.mysql.MySQLExceptionSorter"
                    - name: TIMER_SERVICE_DATA_STORE_REFRESH_INTERVAL
                      value: "60000"
                    ## MySQL driver settings END
      ## KIE server deployment config END
      ## MySQL deployment BEGIN
      - metadata:
          name: "[[.KieName]]-mysql"
          labels:
            app: "[[$.ApplicationName]]"
            application: "[[$.ApplicationName]]"
            service: "[[.KieName]]-mysql"
        spec:
          strategy:
            type: Recreate
          triggers:
            - type: ConfigChange
          replicas: 1
          selector:
            deploymentConfig: "[[.KieName]]-mysql"
          template:
            metadata:
              name: "[[.KieName]]-mysql"
              labels:
                deploymentConfig: "[[.KieName]]-mysql"
                app: "[[$.ApplicationName]]"
                application: "[[$.ApplicationName]]"
                service: "[[.KieName]]-mysql"
            spec:
              terminationGracePeriodSeconds: 60
              containers:
                - name: "[[.KieName]]-mysql"
                  image: "[[$.Constants.MySQLImageURL]]"
                  imagePullPolicy: Always
                  livenessProbe:
                    tcpSocket:
                      port: 3306
                    initialDelaySeconds: 30
                    timeoutSeconds: 1
                  readinessProbe:
                    exec:
                      command:
                        - "/bin/sh"
                        - "-i"
                        - "-c"
                        - "MYSQL_PWD=$MYSQL_PASSWORD mysql -h 127.0.0.1 -u $MYSQL_USER -D $MYSQL_DATABASE -e 'SELECT 1'"
                      port: 3306
                    initialDelaySeconds: 5
                    timeoutSeconds: 1
                  ports:
                    - containerPort: 3306
                      protocol: TCP
                  env:
                    - name: MYSQL_USER
                      value: "rhpam"
                    - name: MYSQL_PASSWORD
                      value: "[[$.DBPassword]]"
                    - name: MYSQL_DATABASE
                      value: "rhpam7"
                  volumeMounts:
                    - mountPath: "/var/lib/mysql/data"
                      name: "[[.KieName]]-mysql-[[$.Constants.DatabaseVolumeSuffix]]"
              ## [[ if ne .Database.Size "" ]]
              volumes:
                - name: "[[.KieName]]-mysql-[[$.Constants.DatabaseVolumeSuffix]]"
                  persistentVolumeClaim:
                    claimName: "[[.KieName]]-mysql-claim"
    ## MySQL persistent volume claim BEGIN
    persistentVolumeClaims:
      - metadata:
          name: "[[.KieName]]-mysql-claim"
          labels:
            app: "[[$.ApplicationName]]"
            application: "[[$.ApplicationName]]"
            service: "[[.KieName]]-mysql"
        spec:
          # [[ if ne .Database.StorageClassName "" ]]
          storageClassName: "[[.Database.StorageClassName]]"
          # [[ end ]]
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: "[[.Database.Size]]"
              ## MySQL persistent volume claim END
              ## [[ else ]]
              volumes:
                - name: "[[.KieName]]-mysql-[[$.Constants.DatabaseVolumeSuffix]]"
                  emptyDir: {}
    ## [[ end ]]
    ## MySQL deployment END
    services:
      - spec:
          ports:
            - port: 3306
              targetPort: 3306
          selector:
            deploymentConfig: "[[.KieName]]-mysql"
        metadata:
          name: "[[.KieName]]-mysql"
          labels:
            app: "[[$.ApplicationName]]"
            application: "[[$.ApplicationName]]"
            service: "[[.KieName]]-mysql"
          annotations:
            description: The MySQL server's port.
  #[[end]]
  ## RANGE ends
## KIE Servers END
