## KIE Servers BEGIN
servers:
  ## RANGE BEGINS
  #[[ range $index, $Map := .Servers ]]
  ## KIE server deployment config BEGIN
  - deploymentConfigs:
      - metadata:
          name: "[[.KieName]]"
        spec:
          template:
            spec:
              initContainers:
                - command:
                    [
                      "sh",
                      "-c",
                      "until nslookup [[.KieName]]-postgresql && nc -vz [[.KieName]]-postgresql 5432; do echo waiting for [[.KieName]]-postgresql; sleep 2; done;",
                    ]
                  image: busybox
                  imagePullPolicy: IfNotPresent
                  name: "[[.KieName]]-postgresql-init"
                  terminationMessagePolicy: FallbackToLogsOnError
              containers:
                - name: "[[.KieName]]"
                  env:
                    ## PostgreSQL driver settings BEGIN
                    - name: DATASOURCES
                      value: "RHPAM"
                    - name: RHPAM_DATABASE
                      value: "rhpam7"
                    - name: RHPAM_JNDI
                      value: "java:/jboss/datasources/rhpam"
                    - name: RHPAM_JTA
                      value: "true"
                    - name: KIE_SERVER_PERSISTENCE_DS
                      value: "java:/jboss/datasources/rhpam"
                    - name: RHPAM_DRIVER
                      value: "postgresql"
                    - name: KIE_SERVER_PERSISTENCE_DIALECT
                      value: "org.hibernate.dialect.PostgreSQLDialect"
                    - name: RHPAM_USERNAME
                      value: "rhpam"
                    - name: RHPAM_PASSWORD
                      value: "[[$.DBPassword]]"
                    - name: RHPAM_SERVICE_HOST
                      value: "[[.KieName]]-postgresql"
                    - name: RHPAM_SERVICE_PORT
                      value: "5432"
                    - name: RHPAM_CONNECTION_CHECKER
                      value: "org.jboss.jca.adapters.jdbc.extensions.postgres.PostgreSQLValidConnectionChecker"
                    - name: RHPAM_EXCEPTION_SORTER
                      value: "org.jboss.jca.adapters.jdbc.extensions.postgres.PostgreSQLExceptionSorter"
                    - name: TIMER_SERVICE_DATA_STORE_REFRESH_INTERVAL
                      value: "30000"
                    ## PostgreSQL driver settings END
      ## KIE server deployment config END
      ## PostgreSQL deployment config BEGIN
      - metadata:
          name: "[[.KieName]]-postgresql"
          labels:
            app: "[[$.ApplicationName]]"
            application: "[[$.ApplicationName]]"
            service: "[[.KieName]]-postgresql"
        spec:
          strategy:
            rollingParams:
              maxSurge: 100%
              maxUnavailable: 0
            type: Rolling
          triggers:
            - type: ImageChange
              imageChangeParams:
                automatic: true
                containerNames:
                  - "[[.KieName]]-postgresql"
                from:
                  kind: ImageStreamTag
                  namespace: "openshift"
                  name: "postgresql:10"
            - type: ConfigChange
          replicas: 1
          selector:
            deploymentConfig: "[[.KieName]]-postgresql"
          template:
            metadata:
              name: "[[.KieName]]-postgresql"
              labels:
                deploymentConfig: "[[.KieName]]-postgresql"
                app: "[[$.ApplicationName]]"
                application: "[[$.ApplicationName]]"
                service: "[[.KieName]]-postgresql"
            spec:
              containers:
                - name: "[[.KieName]]-postgresql"
                  image: postgresql
                  imagePullPolicy: IfNotPresent
                  livenessProbe:
                    exec:
                      command:
                        - "/usr/libexec/check-container"
                        - "--live"
                    initialDelaySeconds: 120
                    timeoutSeconds: 10
                  readinessProbe:
                    exec:
                      command:
                        - "/usr/libexec/check-container"
                    initialDelaySeconds: 5
                    timeoutSeconds: 1
                  ports:
                    - containerPort: 5432
                      protocol: TCP
                  env:
                    - name: POSTGRESQL_USER
                      value: "rhpam"
                    - name: POSTGRESQL_PASSWORD
                      value: "[[$.DBPassword]]"
                    - name: POSTGRESQL_DATABASE
                      value: "rhpam7"
                    - name: POSTGRESQL_MAX_PREPARED_TRANSACTIONS
                      value: "100"
                  volumeMounts:
                    - mountPath: "/var/lib/pgsql/data"
                      name: "[[.KieName]]-postgresql-[[$.Constants.DatabaseVolumeSuffix]]"
              ## [[ if ne .Database.Size "" ]]
              volumes:
                - name: "[[.KieName]]-postgresql-[[$.Constants.DatabaseVolumeSuffix]]"
                  persistentVolumeClaim:
                    claimName: "[[.KieName]]-postgresql-claim"
    ## PostgreSQL deployment config END
    ## PostgreSQL persistent volume claim BEGIN
    persistentVolumeClaims:
      - metadata:
          name: "[[.KieName]]-postgresql-claim"
          labels:
            app: "[[$.ApplicationName]]"
            application: "[[$.ApplicationName]]"
            service: "[[.KieName]]-postgresql"
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: "[[.Database.Size]]"
              ## PostgreSQL persistent volume claim END
              ## [[ else ]]
              volumes:
                - name: "[[.KieName]]-postgresql-[[$.Constants.DatabaseVolumeSuffix]]"
                  emptyDir: {}
    ## [[ end ]]
    services:
      ## PostgreSQL service BEGIN
      - metadata:
          annotations:
            description: The database server's port.
          labels:
            application: prod
            service: "[[.KieName]]-postgresql"
          name: "[[.KieName]]-postgresql"
        spec:
          ports:
            - port: 5432
              targetPort: 5432
          selector:
            deploymentConfig: "[[.KieName]]-postgresql"
    ## PostgreSQL service END
  #[[end]]
  ## RANGE ends
  ## KIE Servers END
