apiVersion: app.kiegroup.org/v2
kind: KieApp
metadata:
  name: rhpam-production-immutable
  annotations:
    consoleName: rhpam-production-immutable
    consoleTitle: BAMOE Production Immutable
    consoleDesc: Deploys a BAMOE Production Immutable environment
spec:
  environment: rhpam-production-immutable
  objects:
    servers:
      - build:
          kieServerContainerDeployment: rhpam-kieserver-library=org.openshift.quickstarts:rhpam-kieserver-library:1.6.0-SNAPSHOT
          gitSource:
            uri: https://github.com/jboss-container-images/rhpam-7-openshift-image.git
            reference: main
            contextDir: quickstarts/library-process/library
