apiVersion: app.kiegroup.org/v2
kind: KieApp
metadata:
  name: rhpam-process-migration
  annotations:
    consoleName: rhpam-process-migration
    consoleTitle: Red Hat Process Automation Process Instance Migration
    consoleDesc: Deploys a BAMOE Process Instance Migration environment
spec:
  environment: rhpam-trial
  objects:
    processMigration:
      username: pimAdmin
      password: somePasswordThatWillBeConvertedToMD5
      database:
        type: "postgresql"
        size: 1Gi
        storageClassName: gold
