apiVersion: app.kiegroup.org/v1
kind: KieApp
metadata:
  name: rhdm-production-immutable-jms
spec:
  environment: rhdm-production-immutable
  objects:
    servers:
      - build:
          kieServerContainerDeployment: rhdm-kieserver-hellorules=org.openshift.quickstarts:rhdm-kieserver-hellorules:1.5.0-SNAPSHOT
          gitSource:
            uri: https://github.com/jboss-container-images/rhdm-7-openshift-image.git
            reference: master
            contextDir: quickstarts/hello-rules/hellorules
        jms:
          enableKieServerJMSIntegration: true
          kieServerJmsEnableSignal: true
          kieServerJmsEnableAudit: true