## KIE Servers BEGIN
servers:
  ## RANGE BEGINS
  #[[ range $index, $Map := .Servers ]]
    ## KIE server deployment config BEGIN
  - deploymentConfigs:
      - metadata:
          name: "[[.KieName]]"
        spec:
          template:
            spec:
              containers:
                - name: "[[.KieName]]"
                  env:
                    ## ExternalDB settings BEGIN
                    - name: KIE_SERVER_PERSISTENCE_DIALECT
                      value: "[[.Database.ExternalConfig.Dialect]]"
                    - name: DATASOURCES
                      value: "RHPAM"
                    - name: RHPAM_DATABASE
                      value: "[[.Database.ExternalConfig.Name]]"
                    - name: RHPAM_SERVICE_HOST
                      value: "[[.Database.ExternalConfig.Host]]"
                    - name: RHPAM_SERVICE_PORT
                      value: "[[.Database.ExternalConfig.Port]]"
                    - name: RHPAM_JNDI
                      value: "java:/jboss/datasources/rhpam"
                    - name: RHPAM_DRIVER
                      value: "[[.Database.ExternalConfig.Driver]]"
                    - name: RHPAM_USERNAME
                      value: "[[.Database.ExternalConfig.Username]]"
                    - name: RHPAM_PASSWORD
                      value: "[[.Database.ExternalConfig.Password]]"
                    - name: RHPAM_NONXA
                      value: "[[.Database.ExternalConfig.NonXA]]"
                    - name: RHPAM_URL
                      value: "[[.Database.ExternalConfig.JdbcURL]]"
                    - name: RHPAM_XA_CONNECTION_PROPERTY_URL
                      value: "[[.Database.ExternalConfig.JdbcURL]]"
                    - name: RHPAM_MIN_POOL_SIZE
                      value: "[[.Database.ExternalConfig.MinPoolSize]]"
                    - name: RHPAM_MAX_POOL_SIZE
                      value: "[[.Database.ExternalConfig.MaxPoolSize]]"
                    - name: RHPAM_CONNECTION_CHECKER
                      value: "[[.Database.ExternalConfig.ConnectionChecker]]"
                    - name: RHPAM_EXCEPTION_SORTER
                      value: "[[.Database.ExternalConfig.ExceptionSorter]]"
                    - name: RHPAM_BACKGROUND_VALIDATION
                      value: "[[.Database.ExternalConfig.BackgroundValidation]]"
                    - name: RHPAM_VALIDATION_MILLIS
                      value: "[[.Database.ExternalConfig.BackgroundValidationMillis]]"
                    - name: RHPAM_JTA
                      value: "true"
                    - name: TIMER_SERVICE_DATA_STORE_REFRESH_INTERVAL
                      value: "10000"
                    ## ExternalDB settings END
      ## KIE server deployment config END
    ## KIE server build config BEGIN
    #[[if .Build.ExtensionImageStreamTag]]
    imageStreams:
      - metadata:
          name: "[[.KieName]]"
          labels:
            app: "[[$.ApplicationName]]"
            application: "[[$.ApplicationName]]"
            service: "[[.KieName]]"
    buildConfigs:
      - metadata:
          name: "[[.KieName]]"
          labels:
            app: "[[$.ApplicationName]]"
            application: "[[$.ApplicationName]]"
            service: "[[.KieName]]"
          annotations:
            template.alpha.openshift.io/wait-for-ready: "true"
        spec:
          source:
            images:
              - from:
                  kind: ImageStreamTag
                  namespace: "[[.Build.ExtensionImageStreamTagNamespace]]"
                  name: "[[.Build.ExtensionImageStreamTag]]"
                paths:
                  - destinationDir: "./extensions/extras"
                    sourcePath: "[[.Build.ExtensionImageInstallDir]]/."
          strategy:
            type: Source
            sourceStrategy:
              env:
                - name: CUSTOM_INSTALL_DIRECTORIES
                  value: "extensions/*"
              forcePull: true
              from:
                kind: "[[.Build.From.Kind]]"
                namespace: "[[.Build.From.Namespace]]"
                name: "[[.Build.From.Name]]"
          output:
            to:
              kind: ImageStreamTag
              name: "[[.KieName]]:latest"
          triggers:
            - type: ImageChange
              imageChange: {}
            - type: ImageChange
              imageChange:
                from:
                  kind: ImageStreamTag
                  namespace: "[[.Build.ExtensionImageStreamTagNamespace]]"
                  name: "[[.Build.ExtensionImageStreamTag]]"
            - type: ConfigChange
    #[[end]]
    ## KIE server build config END
  #[[end]]
  ## RANGE ends
  ## KIE Servers END
